### ISSUE TITLE
Data Loss in Partition Gaps

### ISSUE THREAD

**Issue by FarzamMohammadi** [Azure-Samples/azure-search-dotnet-utilities#4] opened 2023-10-12 19:48 UTC
Hi!

I've discovered a problem with the "partition-index" command, which is used to create index partitions. It works well for the most part, but occasionally, gaps in the partitions result in some actual data being omitted.

I initially thought the gaps between partitions were intended to prevent filtering for a date where there is no data. However, that's not the case. There have been instances where data exists in my index within those gaps, but it's not retrieved.

The partition JSON file always reflects accurate counts, but the data retrieved doesn't align with the expected count.

**Comment by mattgotteiner** [comment] 2024-01-04 22:09
Thanks for reporting! We'll try to reproduce this

**Comment by mattgotteiner** [comment] 2024-01-13 00:21
#8  should help - @FarzamMohammadi  please let me know if you can try again

**Comment by FarzamMohammadi** [comment] 2024-01-13 02:03
Thanks @mattgotteiner. I forked it and refined the features to suit my team's needs. Hopefully, the next users will benefit from your changes.

**Comment by FarzamMohammadi** [comment] 2024-01-13 02:09
Thanks @mattgotteiner, awesome work! Unfortunately, I won't be trying this again. I forked this a while ago and refined the features to suit my team's needs. Hopefully, the next users will benefit from your changes.

**Comment by HeidiSteen** [comment] 2024-01-19 00:31
It sounds like the issue is resolved.  I'm going to close this, but please reopen if there is further action required.

**Closed as completed by HeidiSteen** 2024-01-19 00:31 UTC
